

server:
  port: 18070

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false      # 不向其他 Eureka 注册
    fetchRegistry: false           # 不从其他 Eureka 获取注册表
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
#  cloud:
#    config:
#      uri: http://configserver:18081
#      enabled: true
  config:
    import: optional:configserver:http://configserver:18081/
