<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mwu</groupId>
    <artifactId>v3</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>c1</module>
        <module>c1/high-coupling</module>
        <module>c1/low-coupling</module>
        <module>c1/low-cohesion</module>
        <module>c1/high-cohesion</module>
        <module>c1/5-solid-srp</module>
        <module>c1/6open-closed</module>
        <module>c1/7liskov-substitution</module>
        <module>c1/8interface-segration</module>
        <module>c1/9dependency-inversion</module>
        <module>c2</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>