spring:
  application:
    name: config-server
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
       # git:
        #  uri: https://github.com/zhangxiaoyu-zidif/spring-cloud-config-repo.git
        #  searchPaths: configserver



management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 18081